### ISSUE TITLE
Storybook doesn't display Docs page

### ISSUE THREAD

**Issue by morewings** [storybookjs/builder-vite#128]
MDX story is not rendering for `0.1.3` version. I see these two messages in console:
```
render was not supported :( !
renderToDOM was not supported :( !
```

MRP is available here https://github.com/morewings/forge/tree/master/packages/library-vite

**Comment by blowsie** [comment]
I ran into something similar, although I haven't confirmed its directly related to storybook-vite

![image](https://user-images.githubusercontent.com/308572/160837223-3973fba8-9209-42b9-a792-b297dd56c306.png)


**Reproduction**
https://github.com/blowsie/vue3-vitesse-storybook-pnpm/tree/master/packages/ui

**Comment by IanVS** [comment]
@blowsie can you please try upgrading to the latest version of storybook-builder-vite?

**Comment by IanVS** [comment]
Oh I see in your reproduction that you have.  Hmmmmm.  I'll take a look.

**Comment by blowsie** [comment]
> Oh I see in your reproduction that you have. Hmmmmm. I'll take a look. This should have been fixed in 0.1.22. maybe try clearing your node_modules and browser cache, just in case?

This was a clean installation today, I `rimraf node_modules` a few times whilst getting things up and running, and have cache disabled in my browser when dev tools is open

**Comment by IanVS** [comment]
@blowsie I cloned your repo, tried to npm install and got errors about artifactory, removed the package-lock.json, ran `npm i` (in the sub-package), and `npm run storybook` worked fine, showing the story correctly.  I then removed node_modules, and ran `pnpm i` in the root project, and then again, `npm run storybook` in the ui project, and that worked fine too.  I think you must somehow have an old version of the builder, perhaps in a parent node_modules.  If you're still having troubles, would you mind opening a new issue, since I don't think it's related to the one in this issue.

Speaking of which, since 6.4.0 has been released I'm going to close out this issue.  If anyone still has problems that isn't already captured in another issue, please open one with a reproduction repo, that's extremely helpful.

**Comment by blowsie** [comment]
@IanVS just to be sure, did you check the docs tab?

**Comment by IanVS** [comment]
@blowsie yep, works fine! 
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/4616705/160936440-08ccbb96-05be-4b4a-8de9-7b6932ff1816.png">
