### ISSUE TITLE
Stories in Docs view are sorted alphabetically

### ISSUE THREAD

**Issue by IanVS** [storybookjs/builder-vite#227]
Stories are shown in the sidebar in the correct order, but they are ordered in the docs view alphabetically.

I've confirmed this is the case when using the latest storybook-builder-vite (0.1.15) and storybook 6.4.18.

**Comment by joshwooding** [comment]
This is going to be a long description 😆 

This is because the docs page show the stories in export order which is always alphabetical. It was mentioned in this [comment](https://github.com/storybookjs/storybook/issues/15574#issuecomment-913322881) that the DocsPage Primary was being replaced.

This is because Primary.tsx [calls componentStories()](https://github.com/storybookjs/storybook/blob/64c31900964aa15420e6ec4e1d12f0b88961a457/addons/docs/src/blocks/Primary.tsx#L16) defined here: https://github.com/storybookjs/storybook/blob/64c31900964aa15420e6ec4e1d12f0b88961a457/lib/preview-web/src/PreviewWeb.tsx#L502 which is passed the csfFile from a couple lines above which is fetched using [loadCSFFileByStoryId()]( https://github.com/storybookjs/storybook/blob/64c31900964aa15420e6ec4e1d12f0b88961a457/lib/store/src/StoryStore.ts#L122-L128) which calls the importFn and passes the result to `processCSFFileWithCache()` which seems to intentionally not respect `__namedExportsOrder` judging by this test: https://github.com/storybookjs/storybook/blob/64c31900964aa15420e6ec4e1d12f0b88961a457/lib/store/src/csf/processCSFFile.test.ts#L51-L71.

Now that explanation is out of the way @shilman and @tmeasday (since you both were on the PR 🙂) do you have any thoughts on what we should do here?

**Comment by tmeasday** [comment]
OK, looks like this comment was a mistake @shilman: https://github.com/storybookjs/storybook/pull/16626#pullrequestreview-799609582

I think maybe we should revert that part of the change, the sorting of exports in `processCSFFile()` is not useless after all!

**Comment by IanVS** [comment]
@tmeasday @shilman should we open an issue in the storybook repo?  Or is this being worked on already?

**Comment by Joeycz** [comment]
I got the same problem

**Comment by tmeasday** [comment]
I think that'd be great (the PR) but maybe @shilman can confirm, just in case?

**Comment by sebastienbarre** [comment]
Thanks guys for looking into this. Just switched from Webpack to this builder, and this took me by surprise rather immediately.

**Comment by IanVS** [comment]
@sebastienbarre it looks like @shilman is taking a look at how to fix this (https://github.com/storybookjs/storybook/pull/17793#issuecomment-1078835804), let's see if we can't take care of it before adding it to that list of issues.

**Comment by tmeasday** [comment]
@joshwooding sorry for not making the connection here until now, but I think we fixed the problem you describe with `componentStories()` not using the **story index order** in [this PR](https://github.com/storybookjs/storybook/pull/17669) (on the 9th of March), which was released in `alpha.47`.

Are you sure this issue is still active? It sounds like @sebastienbarre is saying it is, but maybe they aren't on the latest alpha?

**Comment by sebastienbarre** [comment]
@tmeasday yes, sorry, I'm not on the alpha, I'm using v6.4.19. Will this land in the 6.x? Thank you.

**Comment by IanVS** [comment]
Oh awesome, I just checked our examples, which are on `6.5.0-alpha.49`, and the story order is working correctly now.  @sebastienbarre, this will land in 6.5.0 stable.

Closing this issue as fixed by https://github.com/storybookjs/storybook/pull/17669.  Thanks @tmeasday!

**Comment by tmeasday** [comment]
Thanks all! No need to apologies @sebastienbarre just trying to clear up my own confusion :)

**Comment by joshwooding** [comment]
> @joshwooding sorry for not making the connection here until now, but I think we fixed the problem you describe with `componentStories()` not using the **story index order** in [this PR](https://github.com/storybookjs/storybook/pull/17669) (on the 9th of March), which was released in `alpha.47`.
> 
> 
> 
> Are you sure this issue is still active? It sounds like @sebastienbarre is saying it is, but maybe they aren't on the latest alpha?

Ah awesome 😄
