### ISSUE TITLE
[Bug] Error: [vite-plugin-mdx] "@mdx-js/preact" must be installed

### ISSUE THREAD

**Issue by MichaelBitard** [storybookjs/builder-vite#406]
### What version of `vite` are you using?

0.1.36

### System info and storybook versions

 
 System:
    OS: Linux 5.17 Fedora Linux 36 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 17.8.0 - /opt/tools/node/bin/node
    Yarn: 1.22.18 - /opt/tools/node/bin/yarn
    npm: 8.9.0 - /opt/clients/camino/camino/node_modules/.bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0

### Describe the Bug

I think this transitive dependency is problematic, because I don't even use mdx for my storybooks.

I have to install it manually

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by IanVS** [comment]
This looks to be related to https://github.com/storybookjs/builder-vite/issues/391.  Unfortunately we're in a transitional period with mdx1 and mdx2, and still finding a good way to support them both.  The workaround of installing the package manually is your best bet for now.

**Comment by giannif** [comment]
I'm having this issue because in my monorepo (yarn workspace + turbo) one of my packages uses a package that has preact, that makes it try to require `@mdx-js/preact`, even though my storybook is all React components.

If I remove all references to Preact from my monorepo, everything works. 

I think [here](https://github.com/brillout/vite-plugin-mdx/blob/d8a8380a49886d146c0c438500b281655f73b0ad/src/imports.ts#L62) is where that decision is made

Can there be a configuration option to override that?

**Comment by IanVS** [comment]
Hmmmm, @giannif could you try using `nohoist` to keep preact inside the package which uses it, rather than hoisting it up to the top-level node_modules?

**Comment by giannif** [comment]
@IanVS great idea, works, thanks!

**Comment by MichaelBitard** [comment]
Is there a way to disable mdx support at the dependency level? We don't plan to use it anyway
